// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

@com.google.protobuf.Generated
public interface CloudStorageServiceUploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloudstorage.v1.CloudStorageServiceUploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  com.cloudstorage.proto.Status getStatus();

  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   * @return Whether the fileDetails field is set.
   */
  boolean hasFileDetails();
  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   * @return The fileDetails.
   */
  com.cloudstorage.proto.FileDetails getFileDetails();
  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   */
  com.cloudstorage.proto.FileDetailsOrBuilder getFileDetailsOrBuilder();
}
