// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

@com.google.protobuf.Generated
public interface CloudStorageServiceDownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloudstorage.v1.CloudStorageServiceDownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1 [json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
