// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

/**
 * Protobuf type {@code cloudstorage.v1.CloudStorageServiceUploadResponse}
 */
@com.google.protobuf.Generated
public final class CloudStorageServiceUploadResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cloudstorage.v1.CloudStorageServiceUploadResponse)
    CloudStorageServiceUploadResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "CloudStorageServiceUploadResponse");
  }
  // Use CloudStorageServiceUploadResponse.newBuilder() to construct.
  private CloudStorageServiceUploadResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CloudStorageServiceUploadResponse() {
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloudstorage.proto.MainProto.internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloudstorage.proto.MainProto.internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloudstorage.proto.CloudStorageServiceUploadResponse.class, com.cloudstorage.proto.CloudStorageServiceUploadResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.cloudstorage.proto.Status getStatus() {
    com.cloudstorage.proto.Status result = com.cloudstorage.proto.Status.forNumber(status_);
    return result == null ? com.cloudstorage.proto.Status.UNRECOGNIZED : result;
  }

  public static final int FILE_DETAILS_FIELD_NUMBER = 2;
  private com.cloudstorage.proto.FileDetails fileDetails_;
  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   * @return Whether the fileDetails field is set.
   */
  @java.lang.Override
  public boolean hasFileDetails() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   * @return The fileDetails.
   */
  @java.lang.Override
  public com.cloudstorage.proto.FileDetails getFileDetails() {
    return fileDetails_ == null ? com.cloudstorage.proto.FileDetails.getDefaultInstance() : fileDetails_;
  }
  /**
   * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
   */
  @java.lang.Override
  public com.cloudstorage.proto.FileDetailsOrBuilder getFileDetailsOrBuilder() {
    return fileDetails_ == null ? com.cloudstorage.proto.FileDetails.getDefaultInstance() : fileDetails_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.cloudstorage.proto.Status.STATUS_SUCCESS_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getFileDetails());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.cloudstorage.proto.Status.STATUS_SUCCESS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFileDetails());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloudstorage.proto.CloudStorageServiceUploadResponse)) {
      return super.equals(obj);
    }
    com.cloudstorage.proto.CloudStorageServiceUploadResponse other = (com.cloudstorage.proto.CloudStorageServiceUploadResponse) obj;

    if (status_ != other.status_) return false;
    if (hasFileDetails() != other.hasFileDetails()) return false;
    if (hasFileDetails()) {
      if (!getFileDetails()
          .equals(other.getFileDetails())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasFileDetails()) {
      hash = (37 * hash) + FILE_DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getFileDetails().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloudstorage.proto.CloudStorageServiceUploadResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cloudstorage.v1.CloudStorageServiceUploadResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloudstorage.v1.CloudStorageServiceUploadResponse)
      com.cloudstorage.proto.CloudStorageServiceUploadResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudstorage.proto.MainProto.internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudstorage.proto.MainProto.internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudstorage.proto.CloudStorageServiceUploadResponse.class, com.cloudstorage.proto.CloudStorageServiceUploadResponse.Builder.class);
    }

    // Construct using com.cloudstorage.proto.CloudStorageServiceUploadResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFileDetailsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      fileDetails_ = null;
      if (fileDetailsBuilder_ != null) {
        fileDetailsBuilder_.dispose();
        fileDetailsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloudstorage.proto.MainProto.internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor;
    }

    @java.lang.Override
    public com.cloudstorage.proto.CloudStorageServiceUploadResponse getDefaultInstanceForType() {
      return com.cloudstorage.proto.CloudStorageServiceUploadResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cloudstorage.proto.CloudStorageServiceUploadResponse build() {
      com.cloudstorage.proto.CloudStorageServiceUploadResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cloudstorage.proto.CloudStorageServiceUploadResponse buildPartial() {
      com.cloudstorage.proto.CloudStorageServiceUploadResponse result = new com.cloudstorage.proto.CloudStorageServiceUploadResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cloudstorage.proto.CloudStorageServiceUploadResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileDetails_ = fileDetailsBuilder_ == null
            ? fileDetails_
            : fileDetailsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloudstorage.proto.CloudStorageServiceUploadResponse) {
        return mergeFrom((com.cloudstorage.proto.CloudStorageServiceUploadResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloudstorage.proto.CloudStorageServiceUploadResponse other) {
      if (other == com.cloudstorage.proto.CloudStorageServiceUploadResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasFileDetails()) {
        mergeFileDetails(other.getFileDetails());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetFileDetailsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.cloudstorage.proto.Status getStatus() {
      com.cloudstorage.proto.Status result = com.cloudstorage.proto.Status.forNumber(status_);
      return result == null ? com.cloudstorage.proto.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.cloudstorage.proto.Status value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cloudstorage.v1.Status status = 1 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.cloudstorage.proto.FileDetails fileDetails_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cloudstorage.proto.FileDetails, com.cloudstorage.proto.FileDetails.Builder, com.cloudstorage.proto.FileDetailsOrBuilder> fileDetailsBuilder_;
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     * @return Whether the fileDetails field is set.
     */
    public boolean hasFileDetails() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     * @return The fileDetails.
     */
    public com.cloudstorage.proto.FileDetails getFileDetails() {
      if (fileDetailsBuilder_ == null) {
        return fileDetails_ == null ? com.cloudstorage.proto.FileDetails.getDefaultInstance() : fileDetails_;
      } else {
        return fileDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public Builder setFileDetails(com.cloudstorage.proto.FileDetails value) {
      if (fileDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileDetails_ = value;
      } else {
        fileDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public Builder setFileDetails(
        com.cloudstorage.proto.FileDetails.Builder builderForValue) {
      if (fileDetailsBuilder_ == null) {
        fileDetails_ = builderForValue.build();
      } else {
        fileDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public Builder mergeFileDetails(com.cloudstorage.proto.FileDetails value) {
      if (fileDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          fileDetails_ != null &&
          fileDetails_ != com.cloudstorage.proto.FileDetails.getDefaultInstance()) {
          getFileDetailsBuilder().mergeFrom(value);
        } else {
          fileDetails_ = value;
        }
      } else {
        fileDetailsBuilder_.mergeFrom(value);
      }
      if (fileDetails_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public Builder clearFileDetails() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fileDetails_ = null;
      if (fileDetailsBuilder_ != null) {
        fileDetailsBuilder_.dispose();
        fileDetailsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public com.cloudstorage.proto.FileDetails.Builder getFileDetailsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetFileDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    public com.cloudstorage.proto.FileDetailsOrBuilder getFileDetailsOrBuilder() {
      if (fileDetailsBuilder_ != null) {
        return fileDetailsBuilder_.getMessageOrBuilder();
      } else {
        return fileDetails_ == null ?
            com.cloudstorage.proto.FileDetails.getDefaultInstance() : fileDetails_;
      }
    }
    /**
     * <code>optional .cloudstorage.v1.FileDetails file_details = 2 [json_name = "fileDetails"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cloudstorage.proto.FileDetails, com.cloudstorage.proto.FileDetails.Builder, com.cloudstorage.proto.FileDetailsOrBuilder> 
        internalGetFileDetailsFieldBuilder() {
      if (fileDetailsBuilder_ == null) {
        fileDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cloudstorage.proto.FileDetails, com.cloudstorage.proto.FileDetails.Builder, com.cloudstorage.proto.FileDetailsOrBuilder>(
                getFileDetails(),
                getParentForChildren(),
                isClean());
        fileDetails_ = null;
      }
      return fileDetailsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:cloudstorage.v1.CloudStorageServiceUploadResponse)
  }

  // @@protoc_insertion_point(class_scope:cloudstorage.v1.CloudStorageServiceUploadResponse)
  private static final com.cloudstorage.proto.CloudStorageServiceUploadResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloudstorage.proto.CloudStorageServiceUploadResponse();
  }

  public static com.cloudstorage.proto.CloudStorageServiceUploadResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudStorageServiceUploadResponse>
      PARSER = new com.google.protobuf.AbstractParser<CloudStorageServiceUploadResponse>() {
    @java.lang.Override
    public CloudStorageServiceUploadResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloudStorageServiceUploadResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudStorageServiceUploadResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cloudstorage.proto.CloudStorageServiceUploadResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

