// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

@com.google.protobuf.Generated
public interface FileMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloudstorage.v1.FileMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
