// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

@com.google.protobuf.Generated
public interface FileDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloudstorage.v1.FileDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>uint64 file_size = 2 [json_name = "fileSize"];</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <code>string access_url = 3 [json_name = "accessUrl"];</code>
   * @return The accessUrl.
   */
  java.lang.String getAccessUrl();
  /**
   * <code>string access_url = 3 [json_name = "accessUrl"];</code>
   * @return The bytes for accessUrl.
   */
  com.google.protobuf.ByteString
      getAccessUrlBytes();
}
