// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudstorage/v1/main.proto
// Protobuf Java Version: 4.33.2

package com.cloudstorage.proto;

@com.google.protobuf.Generated
public final class MainProto extends com.google.protobuf.GeneratedFile {
  private MainProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "MainProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_CloudStorageServiceUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_CloudStorageServiceUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_CloudStorageServiceDownloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_CloudStorageServiceDownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_FileDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_FileDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloudstorage_v1_FileMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloudstorage_v1_FileMetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032cloudstorage/v1/main.proto\022\017cloudstora" +
      "ge.v1\"6\n CloudStorageServiceUploadReques" +
      "t\022\022\n\004data\030\001 \001(\014R\004data\"9\n#CloudStorageSer" +
      "viceDownloadResponse\022\022\n\004data\030\001 \001(\014R\004data" +
      "\"\253\001\n!CloudStorageServiceUploadResponse\022/" +
      "\n\006status\030\001 \001(\0162\027.cloudstorage.v1.StatusR" +
      "\006status\022D\n\014file_details\030\002 \001(\0132\034.cloudsto" +
      "rage.v1.FileDetailsH\000R\013fileDetails\210\001\001B\017\n" +
      "\r_file_details\"A\n\"CloudStorageServiceDow" +
      "nloadRequest\022\033\n\tfile_name\030\001 \001(\tR\010fileNam" +
      "e\"f\n\013FileDetails\022\033\n\tfile_name\030\001 \001(\tR\010fil" +
      "eName\022\033\n\tfile_size\030\002 \001(\004R\010fileSize\022\035\n\nac" +
      "cess_url\030\003 \001(\tR\taccessUrl\"+\n\014FileMetaDat" +
      "a\022\033\n\tfile_name\030\001 \001(\tR\010fileName*;\n\006Status" +
      "\022\036\n\032STATUS_SUCCESS_UNSPECIFIED\020\000\022\021\n\rSTAT" +
      "US_FAILED\020\0012\201\002\n\023CloudStorageService\022q\n\006U" +
      "pload\0221.cloudstorage.v1.CloudStorageServ" +
      "iceUploadRequest\0322.cloudstorage.v1.Cloud" +
      "StorageServiceUploadResponse(\001\022w\n\010Downlo" +
      "ad\0223.cloudstorage.v1.CloudStorageService" +
      "DownloadRequest\0324.cloudstorage.v1.CloudS" +
      "torageServiceDownloadResponse0\001B\223\001\n\026com." +
      "cloudstorage.protoB\tMainProtoP\001\242\002\003CXX\252\002\017" +
      "Cloudstorage.V1\272\002\020Cloudstorage_V1_\312\002\017Clo" +
      "udstorage\\V1\342\002\033Cloudstorage\\V1\\GPBMetada" +
      "ta\352\002\020Cloudstorage::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cloudstorage_v1_CloudStorageServiceUploadRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_cloudstorage_v1_CloudStorageServiceUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_CloudStorageServiceUploadRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_CloudStorageServiceDownloadResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_CloudStorageServiceUploadResponse_descriptor,
        new java.lang.String[] { "Status", "FileDetails", });
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_cloudstorage_v1_CloudStorageServiceDownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_CloudStorageServiceDownloadRequest_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_cloudstorage_v1_FileDetails_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_cloudstorage_v1_FileDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_FileDetails_descriptor,
        new java.lang.String[] { "FileName", "FileSize", "AccessUrl", });
    internal_static_cloudstorage_v1_FileMetaData_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_cloudstorage_v1_FileMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloudstorage_v1_FileMetaData_descriptor,
        new java.lang.String[] { "FileName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
